#!/usr/bin/env python3
"""Generate firmware constants and test fixtures from ../shared.

    python3 tools/gen.py

Reads   ../shared/rules.json                -> lib/beachrules/rules_config.h
        ../shared/fixtures/rules-cases.json -> test/test_rules/fixtures.h

Run this after editing anything in shared/, then `pio test -e native`.
Both outputs are committed so the project builds without Python.
"""
import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
SHARED = ROOT.parent / "shared"

DOW = {"Sunday": 0, "Monday": 1, "Tuesday": 2, "Wednesday": 3,
       "Thursday": 4, "Friday": 5, "Saturday": 6}

STATE_ENUM = {
    "beach_day": "BeachDay", "night_time": "NightTime", "indoor_day": "IndoorDay",
    "rain_day": "RainDay", "wind_day": "WindDay", "chilly_day": "ChillyDay",
    "nice_day": "NiceDay", "grey_day": "GreyDay", "just_a_day": "JustADay",
}

HEADER = "// GENERATED by tools/gen.py from {src} — do not edit by hand.\n"


def hhmm(s):
    h, m = s.split(":")
    return int(h) * 60 + int(m)


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def op_value(cond):
    return cond["op"], cond["value"]


def gen_rules_config(rules):
    conds = rules["beachDayConditions"]
    states = {s["id"]: s for s in rules["states"]["priority"]}

    def num_from(text, pattern):
        m = re.search(pattern, text)
        if not m:
            sys.exit(f"gen.py: could not parse {pattern!r} from {text!r}")
        return m.group(1)

    lines = [HEADER.format(src="shared/rules.json"),
             "#pragma once", "", "namespace beach {", ""]
    lines.append(f"constexpr int   RULES_VERSION          = {rules['version']};")
    lines.append(f"constexpr int   ACTIVE_START_HOUR      = {rules['activeBeachHours']['startHour']};")
    lines.append(f"constexpr int   ACTIVE_END_HOUR        = {rules['activeBeachHours']['endHour']};")
    lines.append(f"constexpr int   AQI_FALLBACK_START_HOUR = {rules['aqiDaylightWindow']['fallbackStartHour']};")
    lines.append(f"constexpr int   AQI_FALLBACK_END_HOUR  = {rules['aqiDaylightWindow']['fallbackEndHour']};")
    lines.append(f"constexpr int   SUNNY_CODE_MAX         = {rules['sunnyWeatherCodeMax']['value']};")
    lines.append(f"constexpr int   CLEARING_DEADLINE_HOUR = {rules['clearingDeadlineHour']['value']};")

    op, v = op_value(conds["temp"]);  assert op == ">="
    lines.append(f"constexpr int   TEMP_BEACH_MIN         = {int(v)};   // temp >=")
    op, v = op_value(conds["precipProbability"]);  assert op == "<"
    lines.append(f"constexpr float PRECIP_BEACH_MAX       = {float(v)}f; // precip <")
    op, v = op_value(conds["windSpeed"]);  assert op == "<="
    lines.append(f"constexpr float WIND_BEACH_MAX         = {float(v)}f; // wind <=")
    op, v = op_value(conds["aqi"]);  assert op == "<"
    lines.append(f"constexpr int   AQI_BEACH_MAX          = {int(v)};  // aqi <")
    lines.append(f"constexpr int   SUNSET_BUFFER_MIN      = {conds['time']['sunsetBufferMinutes']};")

    rain = num_from(states["rain_day"]["condition"], r">=\s*(\d+)")
    chilly = num_from(states["chilly_day"]["condition"], r"<\s*(\d+)")
    lines.append(f"constexpr int   RAIN_DAY_PRECIP_MIN    = {rain};   // states.rain_day: precip >=")
    lines.append(f"constexpr int   CHILLY_DAY_TEMP_MAX    = {chilly};   // states.chilly_day: temp <")
    lines.append(f"constexpr int   PARKING_SUNSET_FALLBACK_MIN = {rules['parkingAlert']['activeWindow']['sunsetFallbackMinutes']};")
    lines.append("")
    lines.append("// states.priority, in evaluation order")
    lines.append("struct StateText { const char* id; const char* line1; const char* line2; const char* subtitle; };")
    lines.append("constexpr StateText STATE_TEXT[] = {")
    for s in rules["states"]["priority"]:
        title = s["title"]
        # "Beach Day!" -> ("Beach", "Day!"); "Just A Day" -> ("Just A", "Day")
        head, _, tail = title.rpartition(" ")
        lines.append(f"  {{ {cstr(s['id'])}, {cstr(head)}, {cstr(tail)}, {cstr(s['subtitle'])} }},")
    lines.append("};")
    lines.append("")
    lines.append("} // namespace beach")
    return "\n".join(lines) + "\n"


def day_struct(d):
    hours = d["hours"]
    rows = ", ".join(f"{{{9 + i}, {c}}}" for i, c in enumerate(hours))
    return (f"{{ {d['temp']}, {d['tempMin']}, {d['precipProb']}, {d['wind']}, {d['aqi']}, {d['aqiMin']}, "
            f"{d['uv']}, {d['humidityMin']}, {d['humidityMax']}, {d['weatherCode']}, \"\", "
            f"{{ {rows} }}, {len(hours)}, true }}")


def gen_fixtures(fx):
    out = [HEADER.format(src="shared/fixtures/rules-cases.json"), "#pragma once",
           '#include "beachrules.h"', '#include "parking.h"', '#include "aggregate.h"', "",
           "namespace fixtures {", "",
           "constexpr int UNSET = -1;", ""]

    # ---- rules cases
    out.append("struct RulesCase {")
    out.append("  const char* name;")
    out.append("  beach::Inputs in;")
    out.append("  beach::State expectState; bool checkState;")
    out.append("  int expectNight;      // -1 unset, else 0/1")
    out.append("  int cond[6];          // temp, precip, wind, aqi, forecast, time; -1 unset")
    out.append("  const char* sunText;  // nullptr unset")
    out.append("  const char* clearingTime;")
    out.append("  int clearingLater;")
    out.append("  int shownTomorrow;    // -1 unset, 0 today, 1 tomorrow")
    out.append("};")
    out.append("")
    defaults = fx["defaults"]
    out.append("const RulesCase RULES[] = {")
    for c in fx["rulesCases"]:
        today = dict(defaults["day"]); today.update(c.get("today", {}))
        tomorrow = dict(defaults["day"]); tomorrow.update(c.get("tomorrow", {}))
        now = c.get("nowMinutes", defaults["nowMinutes"])
        sr = c.get("sunriseMinutes", defaults["sunriseMinutes"])
        ss = c.get("sunsetMinutes", defaults["sunsetMinutes"])
        e = c["expect"]
        cond = e.get("cond", {})
        flags = [cond.get(k) for k in ("temp", "precip", "wind", "aqi", "forecast", "time")]
        flags = ", ".join("-1" if f is None else ("1" if f else "0") for f in flags)
        state = e.get("state")
        st = f"beach::State::{STATE_ENUM[state]}" if state else "beach::State::JustADay"
        night = e.get("isNight")
        shown = e.get("shown")
        out.append(f"  {{ {cstr(c['name'])},")
        out.append(f"    {{ {now}, {sr}, {ss}, {day_struct(today)}, {day_struct(tomorrow)} }},")
        out.append(f"    {st}, {'true' if state else 'false'}, "
                   f"{-1 if night is None else int(night)}, {{ {flags} }}, "
                   f"{cstr(e['sunText']) if 'sunText' in e else 'nullptr'}, "
                   f"{cstr(e['clearingTime']) if 'clearingTime' in e else 'nullptr'}, "
                   f"{-1 if 'clearingLater' not in e else int(e['clearingLater'])}, "
                   f"{-1 if shown is None else (1 if shown == 'tomorrow' else 0)} }},")
    out.append("};")
    out.append("const int RULES_COUNT = sizeof(RULES) / sizeof(RULES[0]);")
    out.append("")

    # ---- parking cases
    out.append("struct ParkingCase {")
    out.append("  const char* name;")
    out.append("  beach::ParkingRule rules[4]; int ruleCount;")
    out.append("  beach::ParkingInput in;")
    out.append("  bool expectActive; const char* expectText;")
    out.append("};")
    out.append("const ParkingCase PARKING[] = {")
    for c in fx["parkingCases"]:
        rules = c.get("rules", fx["parkingRulesDefault"])
        rs = []
        for r in rules:
            mask = 0
            for w in r["weeks"]:
                mask |= 1 << (w - 1)
            rs.append(f"{{ {'true' if r['enabled'] else 'false'}, {cstr(r['side'])}, {mask}, "
                      f"{DOW[r['day']]}, {hhmm(r['start'])}, {hhmm(r['end'])} }}")
        i = c["input"]
        e = c["expect"]
        out.append(f"  {{ {cstr(c['name'])}, {{ {', '.join(rs)} }}, {len(rs)},")
        out.append(f"    {{ {i['nowMinutes']}, {i['todayDow']}, {i['todayDom']}, {i['tomorrowDow']}, "
                   f"{i['tomorrowDom']}, {i['sunsetMinutes']} }},")
        out.append(f"    {'true' if e['active'] else 'false'}, "
                   f"{cstr(e['text']) if 'text' in e else 'nullptr'} }},")
    out.append("};")
    out.append("const int PARKING_COUNT = sizeof(PARKING) / sizeof(PARKING[0]);")
    out.append("")

    # ---- aggregation cases
    out.append("struct DayExpect {")
    out.append("  int temp, tempMin, precipProb, wind, aqi, aqiMin, uv, humidityMin, humidityMax, weatherCode;")
    out.append("  const char* conditionText; int hourCount, firstHour, firstHourCode, lastHour, lastHourCode;")
    out.append("};")
    out.append("struct AggCase {")
    out.append("  const char* name;")
    out.append("  beach::RawForecast raw;")
    out.append("  int sunriseMinutes, sunsetMinutes;")
    out.append("  DayExpect today, tomorrow;")
    out.append("};")
    dkeys = ["temp", "tempMin", "precipProb", "wind", "aqi", "aqiMin", "uv", "humidityMin",
             "humidityMax", "weatherCode"]
    hkeys = ["hourCount", "firstHour", "firstHourCode", "lastHour", "lastHourCode"]

    def dexp(d):
        vals = ", ".join(str(d.get(k, -1)) for k in dkeys)
        ct = cstr(d["conditionText"]) if "conditionText" in d else "nullptr"
        hv = ", ".join(str(d.get(k, -1)) for k in hkeys)
        return f"{{ {vals}, {ct}, {hv} }}"

    def daily(d):
        return (f"{{ true, {float(d.get('tempMax', 0))!r}, {float(d.get('tempMin', 0))!r}, "
                f"{float(d.get('windMax', 0))!r}, {float(d.get('uvMax', 0))!r}, {d.get('code', 99)}, "
                f"{d.get('precipProbMax', 0)}, {d.get('sunriseMin', 0)}, {d.get('sunsetMin', 0)} }}")

    out.append("const AggCase AGG[] = {")
    for c in fx["aggregationCases"]:
        wx = c.get("wx", [])
        aq = c.get("aqi", [])
        wxs = ", ".join(
            f"{{{r[0]}, {r[1]}, {r[2] if len(r) > 2 else -1}, {r[3] if len(r) > 3 else -1}, {r[4] if len(r) > 4 else -1}}}"
            for r in wx) or "{0,0,-1,-1,-1}"
        aqs = ", ".join(f"{{{r[0]}, {r[1]}, {r[2]}}}" for r in aq) or "{0,0,-1}"
        d0, d1 = c["daily"]
        e = c["expect"]
        out.append(f"  {{ {cstr(c['name'])},")
        out.append(f"    {{ {{ {wxs} }}, {len(wx)}, {{ {aqs} }}, {len(aq)}, {{ {daily(d0)}, {daily(d1)} }} }},")
        out.append(f"    {e.get('sunriseMinutes', -1)}, {e.get('sunsetMinutes', -1)},")
        out.append(f"    {dexp(e.get('today', {}))}, {dexp(e.get('tomorrow', {}))} }},")
    out.append("};")
    out.append("const int AGG_COUNT = sizeof(AGG) / sizeof(AGG[0]);")
    out.append("")
    out.append("} // namespace fixtures")
    return "\n".join(out) + "\n"


def main():
    rules = json.loads((SHARED / "rules.json").read_text())
    fx = json.loads((SHARED / "fixtures" / "rules-cases.json").read_text())

    cfg = ROOT / "lib" / "beachrules" / "rules_config.h"
    cfg.write_text(gen_rules_config(rules))
    print(f"wrote {cfg.relative_to(ROOT)}")

    fxh = ROOT / "test" / "test_rules" / "fixtures.h"
    fxh.parent.mkdir(parents=True, exist_ok=True)
    fxh.write_text(gen_fixtures(fx))
    print(f"wrote {fxh.relative_to(ROOT)}  ({len(fx['rulesCases'])} rules, "
          f"{len(fx['parkingCases'])} parking, {len(fx['aggregationCases'])} aggregation cases)")


if __name__ == "__main__":
    main()
