#!/usr/bin/env python3
"""Prepare the design's typefaces for on-device rendering.

    .venv/bin/python tools/prep_fonts.py

The device rasterises glyphs itself with stb_truetype, so what ships is a
real TTF per face - any size, any panel. Two things are done offline because
stb_truetype does not do them: the variable fonts are instanced to the exact
weights the design uses, and each face is subset to the characters the copy
can contain, which takes Fraunces from 360 KB to a few tens of KB.

Sources come from tools/fetch_fonts.sh (OFL licensed; licences are kept
alongside). Output: src/fontdata.h with one byte array per face.
"""
import io, pathlib
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools import subset

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
SRC = HERE / "fonts"
OUT = ROOT / "src" / "fontdata.h"

# name, source, axis values
FACES = [
    ("FRAUNCES_BLACK",   "Fraunces-Variable.ttf", {"wght": 900, "opsz": 144, "SOFT": 0, "WONK": 0}),
    ("NUNITO_EXTRABOLD", "Nunito-Variable.ttf",   {"wght": 800}),
    ("NUNITO_SEMIBOLD",  "Nunito-Variable.ttf",   {"wght": 600}),
]
# ASCII, degree, middle dot, en/em dash, curly apostrophe and quotes
UNICODES = list(range(0x20, 0x7F)) + [0xB0, 0xB7, 0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D]


def prep(name, source, axes):
    font = TTFont(SRC / source)
    static = instancer.instantiateVariableFont(font, axes, inplace=False, updateFontNames=False)
    opts = subset.Options()
    opts.layout_features = ["kern", "liga"]
    opts.name_IDs = []
    opts.hinting = False           # stb_truetype ignores hints; drop the bytes
    opts.desubroutinize = True
    s = subset.Subsetter(opts)
    s.populate(unicodes=UNICODES)
    s.subset(static)
    buf = io.BytesIO()
    static.save(buf)
    return buf.getvalue()


def main():
    lines = ["// GENERATED by tools/prep_fonts.py - do not edit.",
             "// Fraunces and Nunito, SIL Open Font License; see tools/fonts/OFL-*.txt.",
             "// Static instances at the design's weights, subset to the characters the",
             "// copy can use, ready for stb_truetype on the device.",
             "#pragma once", "#include <stdint.h>", "#include <pgmspace.h>", ""]
    total = 0
    for name, source, axes in FACES:
        data = prep(name, source, axes)
        total += len(data)
        lines.append(f"// {source} {axes} -> {len(data)} bytes")
        lines.append(f"static const uint8_t FONT_{name}[] PROGMEM = {{")
        for i in range(0, len(data), 24):
            lines.append("  " + ",".join(f"0x{b:02X}" for b in data[i:i+24]) + ",")
        lines.append("};")
        lines.append(f"static const uint32_t FONT_{name}_LEN = {len(data)};")
        lines.append("")
        print(f"  {name:18s} {len(data):7d} bytes")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"total {total} bytes -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
