// GENERATED by tools/gen.py from shared/rules.json — do not edit by hand.

#pragma once

namespace beach {

constexpr int   RULES_VERSION          = 1;
constexpr int   ACTIVE_START_HOUR      = 9;
constexpr int   ACTIVE_END_HOUR        = 18;
constexpr int   AQI_FALLBACK_START_HOUR = 6;
constexpr int   AQI_FALLBACK_END_HOUR  = 20;
constexpr int   SUNNY_CODE_MAX         = 2;
constexpr int   CLEARING_DEADLINE_HOUR = 14;
constexpr int   TEMP_BEACH_MIN         = 75;   // temp >=
constexpr float PRECIP_BEACH_MAX       = 20.0f; // precip <
constexpr float WIND_BEACH_MAX         = 15.0f; // wind <=
constexpr int   AQI_BEACH_MAX          = 100;  // aqi <
constexpr int   SUNSET_BUFFER_MIN      = 60;
constexpr int   RAIN_DAY_PRECIP_MIN    = 40;   // states.rain_day: precip >=
constexpr int   CHILLY_DAY_TEMP_MAX    = 65;   // states.chilly_day: temp <
constexpr int   PARKING_SUNSET_FALLBACK_MIN = 1170;

// states.priority, in evaluation order
struct StateText { const char* id; const char* line1; const char* line2; const char* subtitle; };
constexpr StateText STATE_TEXT[] = {
  { "beach_day", "Beach", "Day!", "Pack the car" },
  { "night_time", "Night", "Time", "Beach is closed" },
  { "indoor_day", "Indoor", "Day", "Air Purifier On Max" },
  { "rain_day", "Rain", "Day", "Stay dry" },
  { "wind_day", "Wind", "Day", "Hold your towel" },
  { "chilly_day", "Brrr", "Day", "Wear a hoodie" },
  { "nice_day", "Nice", "Day", "But not quite beachy" },
  { "grey_day", "Grey", "Day", "Seattle vibes" },
  { "just_a_day", "Just A", "Day", "Not beachy" },
};

} // namespace beach
