// GENERATED by tools/gen_icons.py - do not edit. The vector sources live in that script.
// Coordinates are in half-units of a 48x48 box (so 24.5 -> 49); angles in degrees;
// LINEW's first value is a stroke multiplier x10. Roles: 0 ink 1 paper 2 sun 3 water 4 leaf 5 warm.
#pragma once
#include <stdint.h>
#include <pgmspace.h>

enum IcOp : uint8_t { IC_LINE = 0, IC_LINEW = 1, IC_ARC = 2, IC_CIRCLE = 3, IC_DISC = 4, IC_ELLIPSE = 5, IC_ELLIPSE_FILL = 6, IC_RRECT = 7, IC_RRECT_FILL = 8, IC_POLY = 9, IC_POLY_FILL = 10, IC_PIE = 11, IC_UNION_OUTLINE = 12, IC_UNION_FILL = 13 };
struct IcCmd { uint8_t op; uint8_t role; uint8_t n; const int16_t* v; };
struct IconDef { const char* name; const IcCmd* cmds; uint8_t count; };

static const int16_t IC_sun_v[] PROGMEM = { 48, 48, 14, 48, 48, 16, 74, 48, 84, 48, 66, 66, 73, 73, 48, 74, 48, 84, 30, 66, 23, 73, 22, 48, 12, 48, 30, 30, 23, 23, 48, 22, 48, 12, 66, 30, 73, 23 };
static const IcCmd IC_sun[] PROGMEM = {
  { IC_DISC, 2, 3, IC_sun_v + 0 },
  { IC_CIRCLE, 0, 3, IC_sun_v + 3 },
  { IC_LINE, 0, 4, IC_sun_v + 6 },
  { IC_LINE, 0, 4, IC_sun_v + 10 },
  { IC_LINE, 0, 4, IC_sun_v + 14 },
  { IC_LINE, 0, 4, IC_sun_v + 18 },
  { IC_LINE, 0, 4, IC_sun_v + 22 },
  { IC_LINE, 0, 4, IC_sun_v + 26 },
  { IC_LINE, 0, 4, IC_sun_v + 30 },
  { IC_LINE, 0, 4, IC_sun_v + 34 },
};
static const int16_t IC_sun_and_waves_v[] PROGMEM = { 48, 34, 11, 48, 34, 13, 69, 34, 77, 34, 63, 49, 69, 55, 48, 55, 48, 63, 33, 49, 27, 55, 27, 34, 19, 34, 33, 19, 27, 13, 48, 13, 48, 5, 63, 19, 69, 13, 16, 68, 19, 70, 21, 72, 24, 73, 27, 73, 29, 73, 32, 72, 35, 70, 37, 68, 40, 66, 43, 64, 45, 63, 48, 63, 51, 63, 53, 64, 56, 66, 59, 68, 61, 70, 64, 72, 67, 73, 69, 73, 72, 73, 75, 72, 77, 70, 80, 68, 16, 82, 19, 84, 21, 86, 24, 87, 27, 87, 29, 87, 32, 86, 35, 84, 37, 82, 40, 80, 43, 78, 45, 77, 48, 77, 51, 77, 53, 78, 56, 80, 59, 82, 61, 84, 64, 86, 67, 87, 69, 87, 72, 87, 75, 86, 77, 84, 80, 82, 16, 68, 19, 70, 21, 72, 24, 73, 27, 73, 29, 73, 32, 72, 35, 70, 37, 68, 40, 66, 43, 64, 45, 63, 48, 63, 51, 63, 53, 64, 56, 66, 59, 68, 61, 70, 64, 72, 67, 73, 69, 73, 72, 73, 75, 72, 77, 70, 80, 68, 16, 82, 19, 84, 21, 86, 24, 87, 27, 87, 29, 87, 32, 86, 35, 84, 37, 82, 40, 80, 43, 78, 45, 77, 48, 77, 51, 77, 53, 78, 56, 80, 59, 82, 61, 84, 64, 86, 67, 87, 69, 87, 72, 87, 75, 86, 77, 84, 80, 82 };
static const IcCmd IC_sun_and_waves[] PROGMEM = {
  { IC_DISC, 2, 3, IC_sun_and_waves_v + 0 },
  { IC_CIRCLE, 0, 3, IC_sun_and_waves_v + 3 },
  { IC_LINE, 0, 4, IC_sun_and_waves_v + 6 },
  { IC_LINE, 0, 4, IC_sun_and_waves_v + 10 },
  { IC_LINE, 0, 4, IC_sun_and_waves_v + 14 },
  { IC_LINE, 0, 4, IC_sun_and_waves_v + 18 },
  { IC_LINE, 0, 4, IC_sun_and_waves_v + 22 },
  { IC_LINE, 0, 4, IC_sun_and_waves_v + 26 },
  { IC_LINE, 0, 4, IC_sun_and_waves_v + 30 },
  { IC_LINE, 0, 4, IC_sun_and_waves_v + 34 },
  { IC_LINE, 3, 50, IC_sun_and_waves_v + 38 },
  { IC_LINE, 3, 50, IC_sun_and_waves_v + 88 },
  { IC_LINE, 0, 50, IC_sun_and_waves_v + 138 },
  { IC_LINE, 0, 50, IC_sun_and_waves_v + 188 },
};
static const int16_t IC_cloud_v[] PROGMEM = { 4, 0, 34, 52, 14, 0, 50, 42, 18, 0, 66, 52, 13, 1, 20, 52, 79, 66, 7 };
static const IcCmd IC_cloud[] PROGMEM = {
  { IC_UNION_OUTLINE, 0, 19, IC_cloud_v + 0 },
};
static const int16_t IC_rain_cloud_v[] PROGMEM = { 4, 0, 34, 40, 14, 0, 50, 30, 18, 0, 66, 40, 13, 1, 20, 40, 79, 54, 7, 36, 64, 32, 80, 36, 64, 32, 80, 52, 64, 48, 80, 52, 64, 48, 80, 68, 64, 64, 80, 68, 64, 64, 80 };
static const IcCmd IC_rain_cloud[] PROGMEM = {
  { IC_UNION_OUTLINE, 0, 19, IC_rain_cloud_v + 0 },
  { IC_LINE, 3, 4, IC_rain_cloud_v + 19 },
  { IC_LINE, 0, 4, IC_rain_cloud_v + 23 },
  { IC_LINE, 3, 4, IC_rain_cloud_v + 27 },
  { IC_LINE, 0, 4, IC_rain_cloud_v + 31 },
  { IC_LINE, 3, 4, IC_rain_cloud_v + 35 },
  { IC_LINE, 0, 4, IC_rain_cloud_v + 39 },
};
static const int16_t IC_raindrop_v[] PROGMEM = { 1, 0, 48, 58, 18, 48, 18, 31, 52, 65, 52, 48, 58, 18, -20, 200, 31, 50, 48, 18, 65, 50 };
static const IcCmd IC_raindrop[] PROGMEM = {
  { IC_UNION_FILL, 3, 5, IC_raindrop_v + 0 },
  { IC_POLY_FILL, 3, 6, IC_raindrop_v + 5 },
  { IC_ARC, 0, 5, IC_raindrop_v + 11 },
  { IC_LINE, 0, 6, IC_raindrop_v + 16 },
};
static const int16_t IC_wind_v[] PROGMEM = { 16, 34, 60, 34, 60, 26, 8, 90, 360, 16, 50, 72, 50, 72, 58, 8, -90, 180, 16, 66, 48, 66, 48, 74, 8, 90, 360 };
static const IcCmd IC_wind[] PROGMEM = {
  { IC_LINE, 0, 4, IC_wind_v + 0 },
  { IC_ARC, 0, 5, IC_wind_v + 4 },
  { IC_LINE, 0, 4, IC_wind_v + 9 },
  { IC_ARC, 0, 5, IC_wind_v + 13 },
  { IC_LINE, 0, 4, IC_wind_v + 18 },
  { IC_ARC, 0, 5, IC_wind_v + 22 },
};
static const int16_t IC_leaf_v[] PROGMEM = { 22, 74, 32, 36, 74, 22, 64, 60, 23, 23, 51, 0, 90, 73, 73, 51, 180, 270, 28, 68, 64, 32 };
static const IcCmd IC_leaf[] PROGMEM = {
  { IC_POLY_FILL, 4, 8, IC_leaf_v + 0 },
  { IC_ARC, 0, 5, IC_leaf_v + 8 },
  { IC_ARC, 0, 5, IC_leaf_v + 13 },
  { IC_LINE, 0, 4, IC_leaf_v + 18 },
};
static const int16_t IC_thermometer_v[] PROGMEM = { 39, 12, 57, 66, 9, 32, 48, 36, 48, 64, 48, 76, 13, 48, 76, 14 };
static const IcCmd IC_thermometer[] PROGMEM = {
  { IC_RRECT, 0, 5, IC_thermometer_v + 0 },
  { IC_LINEW, 5, 5, IC_thermometer_v + 5 },
  { IC_DISC, 5, 3, IC_thermometer_v + 10 },
  { IC_CIRCLE, 0, 3, IC_thermometer_v + 13 },
};
static const int16_t IC_sun_hat_v[] PROGMEM = { 12, 58, 84, 74, 1, 0, 48, 58, 20, 48, 60, 20, 180, 360, 28, 60, 68, 60 };
static const IcCmd IC_sun_hat[] PROGMEM = {
  { IC_ELLIPSE, 0, 4, IC_sun_hat_v + 0 },
  { IC_UNION_FILL, 2, 5, IC_sun_hat_v + 4 },
  { IC_ARC, 0, 5, IC_sun_hat_v + 9 },
  { IC_LINE, 0, 4, IC_sun_hat_v + 14 },
};
static const int16_t IC_sunscreen_v[] PROGMEM = { 34, 34, 62, 86, 6, 41, 22, 55, 34, 3, 38, 15, 58, 15, 42, 54, 54, 54, 42, 66, 54, 66 };
static const IcCmd IC_sunscreen[] PROGMEM = {
  { IC_RRECT, 0, 5, IC_sunscreen_v + 0 },
  { IC_RRECT, 0, 5, IC_sunscreen_v + 5 },
  { IC_LINE, 0, 4, IC_sunscreen_v + 10 },
  { IC_LINE, 0, 4, IC_sunscreen_v + 14 },
  { IC_LINE, 0, 4, IC_sunscreen_v + 18 },
};
static const int16_t IC_swim_trunks_v[] PROGMEM = { 26, 22, 70, 22, 75, 78, 55, 78, 48, 46, 41, 78, 21, 78, 26, 22, 70, 22, 75, 78, 55, 78, 48, 46, 41, 78, 21, 78, 27, 34, 69, 34 };
static const IcCmd IC_swim_trunks[] PROGMEM = {
  { IC_POLY_FILL, 3, 14, IC_swim_trunks_v + 0 },
  { IC_POLY, 0, 14, IC_swim_trunks_v + 14 },
  { IC_LINE, 0, 4, IC_swim_trunks_v + 28 },
};
static const int16_t IC_towel_v[] PROGMEM = { 24, 18, 72, 82, 10, 24, 40, 72, 40, 24, 60, 72, 60, 40, 24, 50, 72, 50 };
static const IcCmd IC_towel[] PROGMEM = {
  { IC_RRECT, 0, 5, IC_towel_v + 0 },
  { IC_LINE, 0, 4, IC_towel_v + 5 },
  { IC_LINE, 0, 4, IC_towel_v + 9 },
  { IC_LINEW, 3, 5, IC_towel_v + 13 },
};
static const int16_t IC_water_bottle_v[] PROGMEM = { 34, 34, 62, 86, 7, 34, 34, 62, 86, 7, 40, 18, 56, 34, 3, 38, 12, 58, 12, 41, 60, 55, 60 };
static const IcCmd IC_water_bottle[] PROGMEM = {
  { IC_RRECT_FILL, 3, 5, IC_water_bottle_v + 0 },
  { IC_RRECT, 0, 5, IC_water_bottle_v + 5 },
  { IC_RRECT, 0, 5, IC_water_bottle_v + 10 },
  { IC_LINE, 0, 4, IC_water_bottle_v + 15 },
  { IC_LINE, 1, 4, IC_water_bottle_v + 19 },
};
static const int16_t IC_tshirt_v[] PROGMEM = { 18, 24, 35, 14, 61, 14, 78, 24, 71, 40, 62, 36, 62, 82, 34, 82, 34, 36, 25, 40, 48, 15, 10, 0, 180 };
static const IcCmd IC_tshirt[] PROGMEM = {
  { IC_POLY, 0, 20, IC_tshirt_v + 0 },
  { IC_ARC, 0, 5, IC_tshirt_v + 20 },
};
static const int16_t IC_shorts_v[] PROGMEM = { 22, 20, 74, 20, 78, 76, 55, 76, 48, 46, 41, 76, 18, 76, 23, 31, 73, 31 };
static const IcCmd IC_shorts[] PROGMEM = {
  { IC_POLY, 0, 14, IC_shorts_v + 0 },
  { IC_LINE, 0, 4, IC_shorts_v + 14 },
};
static const int16_t IC_sneaker_v[] PROGMEM = { 12, 66, 14, 50, 32, 42, 48, 42, 66, 54, 84, 60, 84, 70, 12, 70, 12, 70, 84, 70, 34, 52, 40, 46, 42, 56, 48, 50 };
static const IcCmd IC_sneaker[] PROGMEM = {
  { IC_POLY, 0, 16, IC_sneaker_v + 0 },
  { IC_LINE, 0, 4, IC_sneaker_v + 16 },
  { IC_LINE, 0, 4, IC_sneaker_v + 20 },
  { IC_LINE, 0, 4, IC_sneaker_v + 24 },
};
static const int16_t IC_sweater_v[] PROGMEM = { 10, 30, 32, 16, 64, 16, 86, 30, 81, 54, 69, 49, 69, 82, 27, 82, 27, 49, 15, 54, 48, 17, 11, 0, 180, 27, 72, 69, 72 };
static const IcCmd IC_sweater[] PROGMEM = {
  { IC_POLY, 0, 20, IC_sweater_v + 0 },
  { IC_ARC, 0, 5, IC_sweater_v + 20 },
  { IC_LINE, 0, 4, IC_sweater_v + 25 },
};
static const int16_t IC_hoodie_v[] PROGMEM = { 10, 30, 32, 16, 64, 16, 86, 30, 81, 54, 69, 49, 69, 82, 27, 82, 27, 49, 15, 54, 48, 17, 11, 0, 180, 27, 72, 69, 72, 48, 20, 18, 190, 350, 40, 30, 38, 54, 56, 30, 58, 54 };
static const IcCmd IC_hoodie[] PROGMEM = {
  { IC_POLY, 0, 20, IC_hoodie_v + 0 },
  { IC_ARC, 0, 5, IC_hoodie_v + 20 },
  { IC_LINE, 0, 4, IC_hoodie_v + 25 },
  { IC_ARC, 0, 5, IC_hoodie_v + 29 },
  { IC_LINE, 0, 4, IC_hoodie_v + 34 },
  { IC_LINE, 0, 4, IC_hoodie_v + 38 },
};
static const int16_t IC_jacket_v[] PROGMEM = { 10, 30, 32, 16, 64, 16, 86, 30, 81, 54, 69, 49, 69, 82, 27, 82, 27, 49, 15, 54, 48, 26, 48, 82, 32, 16, 48, 30, 64, 16 };
static const IcCmd IC_jacket[] PROGMEM = {
  { IC_POLY, 0, 20, IC_jacket_v + 0 },
  { IC_LINE, 0, 4, IC_jacket_v + 20 },
  { IC_LINE, 0, 6, IC_jacket_v + 24 },
};
static const int16_t IC_long_pants_v[] PROGMEM = { 26, 14, 70, 14, 74, 82, 54, 82, 48, 40, 42, 82, 22, 82, 27, 25, 69, 25 };
static const IcCmd IC_long_pants[] PROGMEM = {
  { IC_POLY, 0, 14, IC_long_pants_v + 0 },
  { IC_LINE, 0, 4, IC_long_pants_v + 14 },
};
static const int16_t IC_raincoat_v[] PROGMEM = { 10, 32, 32, 18, 64, 18, 86, 32, 81, 56, 70, 51, 70, 86, 26, 86, 26, 51, 15, 56, 10, 32, 32, 18, 64, 18, 86, 32, 81, 56, 70, 51, 70, 86, 26, 86, 26, 51, 15, 56, 48, 22, 18, 190, 350, 48, 32, 48, 86 };
static const IcCmd IC_raincoat[] PROGMEM = {
  { IC_POLY_FILL, 2, 20, IC_raincoat_v + 0 },
  { IC_POLY, 0, 20, IC_raincoat_v + 20 },
  { IC_ARC, 0, 5, IC_raincoat_v + 40 },
  { IC_LINE, 0, 4, IC_raincoat_v + 45 },
};
static const int16_t IC_rain_boot_v[] PROGMEM = { 26, 12, 54, 12, 54, 54, 84, 69, 84, 82, 22, 82, 22, 12, 26, 12, 54, 12, 54, 54, 84, 69, 84, 82, 22, 82, 22, 12, 22, 23, 54, 23, 22, 72, 84, 72 };
static const IcCmd IC_rain_boot[] PROGMEM = {
  { IC_POLY_FILL, 2, 14, IC_rain_boot_v + 0 },
  { IC_POLY, 0, 14, IC_rain_boot_v + 14 },
  { IC_LINE, 0, 4, IC_rain_boot_v + 28 },
  { IC_LINE, 0, 4, IC_rain_boot_v + 32 },
};
static const int16_t IC_umbrella_v[] PROGMEM = { 48, 50, 36, 180, 360, 48, 50, 36, 180, 360, 24, 50, 12, 0, 180, 48, 50, 12, 0, 180, 72, 50, 12, 0, 180, 48, 14, 48, 50, 48, 50, 48, 76, 41, 76, 7, 0, 180 };
static const IcCmd IC_umbrella[] PROGMEM = {
  { IC_PIE, 5, 5, IC_umbrella_v + 0 },
  { IC_ARC, 0, 5, IC_umbrella_v + 5 },
  { IC_ARC, 0, 5, IC_umbrella_v + 10 },
  { IC_ARC, 0, 5, IC_umbrella_v + 15 },
  { IC_ARC, 0, 5, IC_umbrella_v + 20 },
  { IC_LINE, 0, 4, IC_umbrella_v + 25 },
  { IC_LINE, 0, 4, IC_umbrella_v + 29 },
  { IC_ARC, 0, 5, IC_umbrella_v + 33 },
};
static const int16_t IC_puffy_coat_v[] PROGMEM = { 10, 32, 32, 18, 64, 18, 86, 32, 81, 56, 70, 51, 70, 84, 26, 84, 26, 51, 15, 56, 10, 32, 32, 18, 64, 18, 86, 32, 81, 56, 70, 51, 70, 84, 26, 84, 26, 51, 15, 56, 27, 44, 69, 44, 27, 58, 69, 58, 27, 72, 69, 72, 32, 18, 48, 32, 64, 18 };
static const IcCmd IC_puffy_coat[] PROGMEM = {
  { IC_POLY_FILL, 5, 20, IC_puffy_coat_v + 0 },
  { IC_POLY, 0, 20, IC_puffy_coat_v + 20 },
  { IC_LINE, 0, 4, IC_puffy_coat_v + 40 },
  { IC_LINE, 0, 4, IC_puffy_coat_v + 44 },
  { IC_LINE, 0, 4, IC_puffy_coat_v + 48 },
  { IC_LINE, 0, 6, IC_puffy_coat_v + 52 },
};
static const int16_t IC_beanie_v[] PROGMEM = { 48, 54, 30, 180, 360, 48, 54, 30, 180, 360, 14, 52, 82, 70, 6, 48, 20, 7, 48, 20, 8 };
static const IcCmd IC_beanie[] PROGMEM = {
  { IC_PIE, 5, 5, IC_beanie_v + 0 },
  { IC_ARC, 0, 5, IC_beanie_v + 5 },
  { IC_RRECT, 0, 5, IC_beanie_v + 10 },
  { IC_DISC, 5, 3, IC_beanie_v + 15 },
  { IC_CIRCLE, 0, 3, IC_beanie_v + 18 },
};
static const int16_t IC_mittens_v[] PROGMEM = { 2, 1, 30, 24, 70, 84, 18, 0, 24, 52, 12, 2, 1, 30, 24, 70, 84, 18, 0, 24, 52, 12, 31, 70, 69, 70 };
static const IcCmd IC_mittens[] PROGMEM = {
  { IC_UNION_FILL, 5, 11, IC_mittens_v + 0 },
  { IC_UNION_OUTLINE, 0, 11, IC_mittens_v + 11 },
  { IC_LINE, 0, 4, IC_mittens_v + 22 },
};
static const int16_t IC_scarf_v[] PROGMEM = { 20, 24, 76, 44, 10, 20, 24, 76, 44, 10, 30, 44, 43, 44, 47, 86, 34, 86, 30, 44, 43, 44, 47, 86, 34, 86, 49, 44, 62, 44, 60, 86, 47, 86, 49, 44, 62, 44, 60, 86, 47, 86, 36, 86, 36, 92, 41, 86, 41, 92, 52, 86, 52, 92, 57, 86, 57, 92 };
static const IcCmd IC_scarf[] PROGMEM = {
  { IC_RRECT_FILL, 5, 5, IC_scarf_v + 0 },
  { IC_RRECT, 0, 5, IC_scarf_v + 5 },
  { IC_POLY_FILL, 5, 8, IC_scarf_v + 10 },
  { IC_POLY, 0, 8, IC_scarf_v + 18 },
  { IC_POLY_FILL, 5, 8, IC_scarf_v + 26 },
  { IC_POLY, 0, 8, IC_scarf_v + 34 },
  { IC_LINE, 0, 4, IC_scarf_v + 42 },
  { IC_LINE, 0, 4, IC_scarf_v + 46 },
  { IC_LINE, 0, 4, IC_scarf_v + 50 },
  { IC_LINE, 0, 4, IC_scarf_v + 54 },
};

static const IconDef ICON_DEFS[] PROGMEM = {
  { "sun", IC_sun, 10 },
  { "sun_and_waves", IC_sun_and_waves, 14 },
  { "cloud", IC_cloud, 1 },
  { "rain_cloud", IC_rain_cloud, 7 },
  { "raindrop", IC_raindrop, 4 },
  { "wind", IC_wind, 6 },
  { "leaf", IC_leaf, 4 },
  { "thermometer", IC_thermometer, 4 },
  { "sun_hat", IC_sun_hat, 4 },
  { "sunscreen", IC_sunscreen, 5 },
  { "swim_trunks", IC_swim_trunks, 3 },
  { "towel", IC_towel, 4 },
  { "water_bottle", IC_water_bottle, 5 },
  { "tshirt", IC_tshirt, 2 },
  { "shorts", IC_shorts, 2 },
  { "sneaker", IC_sneaker, 4 },
  { "sweater", IC_sweater, 3 },
  { "hoodie", IC_hoodie, 6 },
  { "jacket", IC_jacket, 3 },
  { "long_pants", IC_long_pants, 2 },
  { "raincoat", IC_raincoat, 4 },
  { "rain_boot", IC_rain_boot, 4 },
  { "umbrella", IC_umbrella, 8 },
  { "puffy_coat", IC_puffy_coat, 6 },
  { "beanie", IC_beanie, 5 },
  { "mittens", IC_mittens, 3 },
  { "scarf", IC_scarf, 10 },
};
static const int ICON_DEF_COUNT = sizeof(ICON_DEFS) / sizeof(ICON_DEFS[0]);
